export interface NeighborhoodData {
  city: string;
  name: string;
  slug: string;
  state: string;
  stateSlug: string;
  powerBand: "Band A (20+ hrs daily)" | "Band B (16-20 hrs daily)" | "Band C (12-16 hrs daily)";
  floodRisk: "Low (Elevated terrain)" | "Moderate (Standard drainage)" | "Minimal / Zero flood risk";
  transitHub: string;
  campusProximity?: string;
  medianRents: {
    apartment: number;
    "1-bedroom-flat": number;
    "2-bedroom-flat": number;
    "3-bedroom-flat": number;
    "self-contain": number;
    duplex: number;
    room: number;
  };
  highlights: string[];
  description: string;
}

export interface StateData {
  name: string;
  slug: string;
  tagline: string;
  description: string;
  popularCities: string[];
}

export interface PropertyTypeMeta {
  slug: string;
  name: string;
  singular: string;
  plural: string;
  prismaEquivalent: string;
  standardBeds: number;
  descriptionTemplate: string;
}

export const PROPERTY_TYPES: Record<string, PropertyTypeMeta> = {
  apartment: {
    slug: "apartment",
    name: "Apartment",
    singular: "Apartment",
    plural: "Apartments",
    prismaEquivalent: "Apartment",
    standardBeds: 2,
    descriptionTemplate: "modern flats and serviced apartments",
  },
  "1-bedroom-flat": {
    slug: "1-bedroom-flat",
    name: "1 Bedroom Flat (Mini Flat)",
    singular: "1 Bedroom Flat",
    plural: "1 Bedroom Flats",
    prismaEquivalent: "Apartment",
    standardBeds: 1,
    descriptionTemplate: "private mini-flats with dedicated living room, kitchen, and ensuite bedroom",
  },
  "2-bedroom-flat": {
    slug: "2-bedroom-flat",
    name: "2 Bedroom Flat",
    singular: "2 Bedroom Flat",
    plural: "2 Bedroom Flats",
    prismaEquivalent: "Apartment",
    standardBeds: 2,
    descriptionTemplate: "spacious 2-bedroom apartments suitable for young professionals and small families",
  },
  "3-bedroom-flat": {
    slug: "3-bedroom-flat",
    name: "3 Bedroom Flat",
    singular: "3 Bedroom Flat",
    plural: "3 Bedroom Flats",
    prismaEquivalent: "Apartment",
    standardBeds: 3,
    descriptionTemplate: "executive 3-bedroom family flats with ample parking and security",
  },
  "self-contain": {
    slug: "self-contain",
    name: "Self Contain (Studio Apartment)",
    singular: "Self Contain",
    plural: "Self Contains",
    prismaEquivalent: "Rooms",
    standardBeds: 1,
    descriptionTemplate: "budget-friendly, fully contained single-room units with private bathroom and kitchenette",
  },
  duplex: {
    slug: "duplex",
    name: "Duplex & Townhouse",
    singular: "Duplex",
    plural: "Duplexes",
    prismaEquivalent: "Townhouse",
    standardBeds: 4,
    descriptionTemplate: "multi-level detached and semi-detached luxury duplexes with private compounds",
  },
  room: {
    slug: "room",
    name: "Single Room / Student Accommodation",
    singular: "Single Room",
    plural: "Single Rooms",
    prismaEquivalent: "Rooms",
    standardBeds: 1,
    descriptionTemplate: "shared and private student rooms within secure gated compounds",
  },
};

export const NIGERIAN_STATES: Record<string, StateData> = {
  lagos: {
    name: "Lagos",
    slug: "lagos",
    tagline: "Commercial capital of Nigeria with high-yield residential corridors",
    description: "Explore verified residential apartments, serviced mini-flats, and luxury duplexes across Lagos Island, Lekki Peninsula, and the bustling Lagos Mainland.",
    popularCities: ["lekki", "yaba", "ikeja", "surulere", "gbagada", "ikoyi", "victoria-island", "ajah", "magodo"],
  },
  abuja: {
    name: "Abuja (FCT)",
    slug: "abuja",
    tagline: "Nigeria's federal capital featuring planned infrastructure and serene estates",
    description: "Find diplomat-grade residences, serviced apartments, and family townhouses in Maitama, Wuse 2, Gwarinpa, and emerging suburban districts.",
    popularCities: ["maitama", "wuse-2", "gwarinpa", "jabi", "utako", "asokoro", "guzape", "lugbe"],
  },
  kwara: {
    name: "Kwara",
    slug: "kwara",
    tagline: "Fast-growing academic and innovation hub with affordable student & family housing",
    description: "Discover verified student hostels, modern self-contain apartments, and family residences near the University of Ilorin (UNILORIN) and Kwara State Polytechnic.",
    popularCities: ["tanke", "sanrab", "oke-odo", "jalala", "mark-junction", "fate", "gra-ilorin"],
  },
  oyo: {
    name: "Oyo",
    slug: "oyo",
    tagline: "Historic and vibrant southwestern city with sprawling residential neighborhoods",
    description: "Browse affordable student and family rentals in Bodija, Agbowo (adjacent to the University of Ibadan), Oluyole, and Ring Road.",
    popularCities: ["bodija", "agbowo", "oluyole", "samonda", "ring-road", "jericho"],
  },
  rivers: {
    name: "Rivers",
    slug: "rivers",
    tagline: "Oil and maritime hub with secure executive estates in Port Harcourt",
    description: "Find prime executive flats, serviced corporate housing, and standalone duplexes in Old GRA, New GRA, and Peter Odili Road.",
    popularCities: ["old-gra", "new-gra", "peter-odili", "trans-amadi", "ada-george"],
  },
  enugu: {
    name: "Enugu",
    slug: "enugu",
    tagline: "Coal City center of commerce, culture, and academic excellence in the Southeast",
    description: "Browse verified residential apartments, mini-flats, and quiet family homes in Independence Layout, New Haven, and GRA Enugu.",
    popularCities: ["independence-layout", "new-haven", "gra-enugu"],
  },
};

export const NEIGHBORHOODS: Record<string, NeighborhoodData> = {
  // LAGOS NEIGHBORHOODS
  "lagos/lekki": {
    city: "Lekki",
    name: "Lekki (Phase 1, Agungi, Chevron, Ikate)",
    slug: "lekki",
    state: "Lagos",
    stateSlug: "lagos",
    powerBand: "Band A (20+ hrs daily)",
    floodRisk: "Moderate (Standard drainage)",
    transitHub: "Direct access to Lekki-Epe Expressway & Admiralty Way",
    medianRents: {
      apartment: 4500000,
      "1-bedroom-flat": 2800000,
      "2-bedroom-flat": 4500000,
      "3-bedroom-flat": 7000000,
      "self-contain": 1800000,
      duplex: 12000000,
      room: 1200000,
    },
    highlights: ["24/7 Serviced Estates", "High-Speed Fiber Internet", "Access to Nightlife & Cafes", "Top-tier Private Security"],
    description: "Lekki is Lagos' premier coastal residential district, offering modern serviced apartments, private estates with steady power, and proximity to Victoria Island.",
  },
  "lagos/yaba": {
    city: "Yaba",
    name: "Yaba (Akoka, Alagomeji, Sabo)",
    slug: "yaba",
    state: "Lagos",
    stateSlug: "lagos",
    powerBand: "Band B (16-20 hrs daily)",
    floodRisk: "Low (Elevated terrain)",
    transitHub: "Direct Third Mainland Bridge ramp & Yaba Railway Hub",
    campusProximity: "5 mins to University of Lagos (UNILAG) & Yaba College of Technology",
    medianRents: {
      apartment: 3200000,
      "1-bedroom-flat": 1800000,
      "2-bedroom-flat": 3200000,
      "3-bedroom-flat": 4800000,
      "self-contain": 900000,
      duplex: 7500000,
      room: 650000,
    },
    highlights: ["Silicon Lagoon Tech Hub", "Walking Distance to UNILAG", "Direct Island Access via 3MB", "Thriving Student & Tech Culture"],
    description: "Yaba is Nigeria's technology cradle and primary higher education corridor. A favorite for tech professionals, startup founders, and students.",
  },
  "lagos/ikeja": {
    city: "Ikeja",
    name: "Ikeja (GRA, Allen Avenue, Opebi)",
    slug: "ikeja",
    state: "Lagos",
    stateSlug: "lagos",
    powerBand: "Band A (20+ hrs daily)",
    floodRisk: "Minimal / Zero flood risk",
    transitHub: "Murtala Muhammed International Airport (MMIA) & Lagos Red Line Train",
    medianRents: {
      apartment: 4000000,
      "1-bedroom-flat": 2200000,
      "2-bedroom-flat": 4000000,
      "3-bedroom-flat": 6500000,
      "self-contain": 1400000,
      duplex: 14000000,
      room: 900000,
    },
    highlights: ["State Government Hub", "Proximity to International Airport", "High Security in GRA", "Uninterrupted Commercial Activity"],
    description: "Ikeja is the capital of Lagos State, blending serene executive residential enclaves in Ikeja GRA with vibrant retail corridors along Allen and Opebi.",
  },
  "lagos/surulere": {
    city: "Surulere",
    name: "Surulere (Bode Thomas, Adeniran Ogunsanya)",
    slug: "surulere",
    state: "Lagos",
    stateSlug: "lagos",
    powerBand: "Band B (16-20 hrs daily)",
    floodRisk: "Low (Elevated terrain)",
    transitHub: "Eko Bridge & Funsho Williams Avenue (Western Avenue)",
    medianRents: {
      apartment: 2800000,
      "1-bedroom-flat": 1600000,
      "2-bedroom-flat": 2800000,
      "3-bedroom-flat": 4200000,
      "self-contain": 850000,
      duplex: 6800000,
      room: 600000,
    },
    highlights: ["Central Lagos Mainland Hub", "Quick Access to Island via Eko Bridge", "Rich Sports & Leisure Scene", "Gated Street Communities"],
    description: "Surulere is an iconic, deeply communal Lagos neighborhood with quiet residential streets, excellent food culture, and rapid links to Lagos Island.",
  },
  "lagos/gbagada": {
    city: "Gbagada",
    name: "Gbagada (Phase 1, Phase 2, Millennium)",
    slug: "gbagada",
    state: "Lagos",
    stateSlug: "lagos",
    powerBand: "Band B (16-20 hrs daily)",
    floodRisk: "Low (Elevated terrain)",
    transitHub: "Oworonshoki Expressway & Third Mainland Bridge corridor",
    medianRents: {
      apartment: 3000000,
      "1-bedroom-flat": 1700000,
      "2-bedroom-flat": 3000000,
      "3-bedroom-flat": 4500000,
      "self-contain": 950000,
      duplex: 7000000,
      room: 700000,
    },
    highlights: ["Strategic Central Point", "Modern Gated Estates", "Easy Island & Airport Commute", "Family-Friendly Ambiance"],
    description: "Gbagada sits at the junction of the Island and Mainland, making it one of the most sought-after rental choices for commuters working on Victoria Island or in Ikeja.",
  },
  "lagos/ikoyi": {
    city: "Ikoyi",
    name: "Ikoyi (Banana Island, Parkview, Old Ikoyi)",
    slug: "ikoyi",
    state: "Lagos",
    stateSlug: "lagos",
    powerBand: "Band A (20+ hrs daily)",
    floodRisk: "Low (Elevated terrain)",
    transitHub: "Lekki-Ikoyi Link Bridge & Osborne Road",
    medianRents: {
      apartment: 12000000,
      "1-bedroom-flat": 6000000,
      "2-bedroom-flat": 12000000,
      "3-bedroom-flat": 22000000,
      "self-contain": 3500000,
      duplex: 35000000,
      room: 2500000,
    },
    highlights: ["Nigeria's Most Prestigious Zip Code", "Top Diplomatic Security", "Waterfront Living", "Dedicated Independent Power"],
    description: "Ikoyi is Nigeria's premier ultra-luxury residential enclave, home to international embassies, business titans, and waterfront high-rises.",
  },
  "lagos/victoria-island": {
    city: "Victoria Island",
    name: "Victoria Island (Oniru, Eko Atlantic, Kofo Abayomi)",
    slug: "victoria-island",
    state: "Lagos",
    stateSlug: "lagos",
    powerBand: "Band A (20+ hrs daily)",
    floodRisk: "Low (Elevated terrain)",
    transitHub: "Ahmadu Bello Way & Ozumba Mbadiwe Avenue",
    medianRents: {
      apartment: 9500000,
      "1-bedroom-flat": 5000000,
      "2-bedroom-flat": 9500000,
      "3-bedroom-flat": 16000000,
      "self-contain": 3000000,
      duplex: 28000000,
      room: 2000000,
    },
    highlights: ["Banking & Financial HQ District", "Fine Dining & High Culture", "Oceanfront Penthouses", "Walking Distance to Work"],
    description: "Victoria Island is the beating financial heart of Nigeria, combining headquarters of major multinationals with high-end serviced corporate flats.",
  },
  "lagos/ajah": {
    city: "Ajah",
    name: "Ajah (Badore, Sangotedo, Abraham Adesanya)",
    slug: "ajah",
    state: "Lagos",
    stateSlug: "lagos",
    powerBand: "Band B (16-20 hrs daily)",
    floodRisk: "Moderate (Standard drainage)",
    transitHub: "Lekki-Epe Expressway & Badore Ferry Terminal",
    medianRents: {
      apartment: 2200000,
      "1-bedroom-flat": 1200000,
      "2-bedroom-flat": 2200000,
      "3-bedroom-flat": 3500000,
      "self-contain": 700000,
      duplex: 5500000,
      room: 500000,
    },
    highlights: ["Affordable Island Living", "Access to Water Transportation", "Expanding Shopping Centers (Novare Mall)", "Rapid Infrastructure Growth"],
    description: "Ajah offers accessible Island rental pricing with modern gated estates, popular shopping malls, and scenic water transport links.",
  },
  "lagos/magodo": {
    city: "Magodo",
    name: "Magodo (GRA Phase 1, Phase 2 Shangisha)",
    slug: "magodo",
    state: "Lagos",
    stateSlug: "lagos",
    powerBand: "Band A (20+ hrs daily)",
    floodRisk: "Minimal / Zero flood risk",
    transitHub: "Lagos-Ibadan Expressway & CMD Road",
    medianRents: {
      apartment: 3800000,
      "1-bedroom-flat": 2000000,
      "2-bedroom-flat": 3800000,
      "3-bedroom-flat": 5500000,
      "self-contain": 1100000,
      duplex: 10000000,
      room: 800000,
    },
    highlights: ["Strict Security Access Gates", "Hilltop Elevated Terrain", "Direct Access to Lagos-Ibadan Express", "Quiet Residential Atmosphere"],
    description: "Magodo GRA is a tranquil residential haven perched on elevated hills, celebrated for its tight security controls and premium family housing.",
  },

  // ABUJA NEIGHBORHOODS
  "abuja/maitama": {
    city: "Maitama",
    name: "Maitama (Diplomatic Zone, Ministers Hill)",
    slug: "maitama",
    state: "Abuja",
    stateSlug: "abuja",
    powerBand: "Band A (20+ hrs daily)",
    floodRisk: "Minimal / Zero flood risk",
    transitHub: "Shehu Shagari Way & IBB Way",
    medianRents: {
      apartment: 15000000,
      "1-bedroom-flat": 7500000,
      "2-bedroom-flat": 15000000,
      "3-bedroom-flat": 25000000,
      "self-contain": 4000000,
      duplex: 45000000,
      room: 3000000,
    },
    highlights: ["Federal Diplomatic Quarter", "24/7 Guaranteed Grid Power", "Maximum Security Zone", "Broad Tree-Lined Boulevards"],
    description: "Maitama is the pinnacle of luxury living in Abuja, hosting foreign embassies, ministers, and international dignitaries.",
  },
  "abuja/wuse-2": {
    city: "Wuse 2",
    name: "Wuse 2 (Adetokunbo Ademola, Aminu Kano)",
    slug: "wuse-2",
    state: "Abuja",
    stateSlug: "abuja",
    powerBand: "Band A (20+ hrs daily)",
    floodRisk: "Minimal / Zero flood risk",
    transitHub: "Aminu Kano Crescent & Ahmadu Bello Way",
    medianRents: {
      apartment: 8000000,
      "1-bedroom-flat": 4000000,
      "2-bedroom-flat": 8000000,
      "3-bedroom-flat": 14000000,
      "self-contain": 2200000,
      duplex: 25000000,
      room: 1800000,
    },
    highlights: ["Abuja's Lifestyle & Dining Capital", "High Commercial Footfall", "Central City Location", "Serviced Executive Suites"],
    description: "Wuse 2 is Abuja's vibrant entertainment and dining epicenter, filled with high-end cafes, boutiques, and prime serviced apartments.",
  },
  "abuja/gwarinpa": {
    city: "Gwarinpa",
    name: "Gwarinpa Estate (1st to 7th Avenue)",
    slug: "gwarinpa",
    state: "Abuja",
    stateSlug: "abuja",
    powerBand: "Band B (16-20 hrs daily)",
    floodRisk: "Low (Elevated terrain)",
    transitHub: "Murtala Mohammed Expressway & Kubwa Expressway",
    medianRents: {
      apartment: 3500000,
      "1-bedroom-flat": 1800000,
      "2-bedroom-flat": 3500000,
      "3-bedroom-flat": 5500000,
      "self-contain": 1000000,
      duplex: 9000000,
      room: 750000,
    },
    highlights: ["West Africa's Largest Housing Estate", "Fully Self-Contained Ecosystem", "Affordable Family Living", "Wide Range of Housing Formats"],
    description: "Gwarinpa is West Africa's largest planned estate, delivering comprehensive amenities, self-contained markets, and affordable family rentals.",
  },
  "abuja/jabi": {
    city: "Jabi",
    name: "Jabi (Jabi Lake, Dapo Ojora)",
    slug: "jabi",
    state: "Abuja",
    stateSlug: "abuja",
    powerBand: "Band A (20+ hrs daily)",
    floodRisk: "Minimal / Zero flood risk",
    transitHub: "Shehu Yar'Adua Way & Obafemi Awolowo Way",
    medianRents: {
      apartment: 6000000,
      "1-bedroom-flat": 3200000,
      "2-bedroom-flat": 6000000,
      "3-bedroom-flat": 10000000,
      "self-contain": 1700000,
      duplex: 18000000,
      room: 1300000,
    },
    highlights: ["Scenic Waterfront Promenade", "Jabi Lake Mall Proximity", "Rapid Access to Central Business District", "Modern Architecture"],
    description: "Jabi features waterfront lifestyle living along Jabi Lake, combining peaceful nature walks with urban shopping and swift CBD access.",
  },
  "abuja/utako": {
    city: "Utako",
    name: "Utako District",
    slug: "utako",
    state: "Abuja",
    stateSlug: "abuja",
    powerBand: "Band B (16-20 hrs daily)",
    floodRisk: "Minimal / Zero flood risk",
    transitHub: "Arab Road & Shehu Yar'Adua Way",
    medianRents: {
      apartment: 4500000,
      "1-bedroom-flat": 2400000,
      "2-bedroom-flat": 4500000,
      "3-bedroom-flat": 7500000,
      "self-contain": 1200000,
      duplex: 13000000,
      room: 900000,
    },
    highlights: ["Central Inter-State Transit Terminals", "Close to Wuse & CBD", "Competitive Rents for Prime Location", "Thriving Local Commerce"],
    description: "Utako is a key transit and commercial hub right next to Wuse, presenting fantastic accessibility and competitive mid-market rental prices.",
  },
  "abuja/asokoro": {
    city: "Asokoro",
    name: "Asokoro (ECOWAS, Presidential Enclave)",
    slug: "asokoro",
    state: "Abuja",
    stateSlug: "abuja",
    powerBand: "Band A (20+ hrs daily)",
    floodRisk: "Minimal / Zero flood risk",
    transitHub: "Yakubu Gowon Crescent & Aso Drive",
    medianRents: {
      apartment: 16000000,
      "1-bedroom-flat": 8000000,
      "2-bedroom-flat": 16000000,
      "3-bedroom-flat": 27000000,
      "self-contain": 4500000,
      duplex: 50000000,
      room: 3500000,
    },
    highlights: ["Adjacent to Aso Rock Villa", "Highest National Security Presence", "Lush Mountainous Scenery", "Ultra-Exclusive Mansions"],
    description: "Asokoro is the administrative power center of Nigeria, boasting scenic hills, maximum security, and high-end ambassadorial homes.",
  },
  "abuja/guzape": {
    city: "Guzape",
    name: "Guzape (Asokoro Extension)",
    slug: "guzape",
    state: "Abuja",
    stateSlug: "abuja",
    powerBand: "Band A (20+ hrs daily)",
    floodRisk: "Minimal / Zero flood risk",
    transitHub: "Guzape Hilltop Expressway & Murtala Mohammed Way",
    medianRents: {
      apartment: 7500000,
      "1-bedroom-flat": 3800000,
      "2-bedroom-flat": 7500000,
      "3-bedroom-flat": 12000000,
      "self-contain": 2000000,
      duplex: 22000000,
      room: 1500000,
    },
    highlights: ["Panoramic Views of Abuja City", "Rapidly Appreciating Modern Enclave", "5 Mins to Asokoro", "Contemporary Architectural Marvels"],
    description: "Guzape is Abuja's fast-rising luxury hill neighborhood, delivering spectacular city skyline vistas and cutting-edge architectural flats.",
  },
  "abuja/lugbe": {
    city: "Lugbe",
    name: "Lugbe (Federal Housing, Airport Road)",
    slug: "lugbe",
    state: "Abuja",
    stateSlug: "abuja",
    powerBand: "Band C (12-16 hrs daily)",
    floodRisk: "Low (Elevated terrain)",
    transitHub: "Nnamdi Azikiwe Airport Expressway",
    medianRents: {
      apartment: 1500000,
      "1-bedroom-flat": 800000,
      "2-bedroom-flat": 1500000,
      "3-bedroom-flat": 2400000,
      "self-contain": 450000,
      duplex: 4500000,
      room: 350000,
    },
    highlights: ["Most Affordable Abuja Commuter Suburb", "Direct Airport Road Freeway", "High Rental Demand", "Federal Housing Authority Schemes"],
    description: "Lugbe is the top budget-friendly commuter suburb along the 10-lane Airport Road, ideal for civil servants and young professionals starting out.",
  },

  // KWARA NEIGHBORHOODS (ILORIN - HIGHEST DENSITY RENTAL MARKET)
  "kwara/tanke": {
    city: "Tanke",
    name: "Tanke (University Road, Tanke Oke)",
    slug: "tanke",
    state: "Kwara",
    stateSlug: "kwara",
    powerBand: "Band B (16-20 hrs daily)",
    floodRisk: "Minimal / Zero flood risk",
    transitHub: "University Road & Tiper Garage corridor",
    campusProximity: "3 mins to University of Ilorin (UNILORIN) Main Gate",
    medianRents: {
      apartment: 850000,
      "1-bedroom-flat": 550000,
      "2-bedroom-flat": 850000,
      "3-bedroom-flat": 1400000,
      "self-contain": 350000,
      duplex: 2500000,
      room: 220000,
    },
    highlights: ["Primary UNILORIN Student Strip", "24/7 Student Cafes & Hubs", "Dedicated Campus Shuttle Routes", "High Turnover Yields"],
    description: "Tanke is the beating heart of student and academic life in Ilorin, situated right on the University of Ilorin approach road.",
  },
  "kwara/sanrab": {
    city: "Sanrab",
    name: "Sanrab (Tanke Sanrab)",
    slug: "sanrab",
    state: "Kwara",
    stateSlug: "kwara",
    powerBand: "Band B (16-20 hrs daily)",
    floodRisk: "Minimal / Zero flood risk",
    transitHub: "Sanrab Junction & University Road",
    campusProximity: "4 mins to University of Ilorin",
    medianRents: {
      apartment: 800000,
      "1-bedroom-flat": 500000,
      "2-bedroom-flat": 800000,
      "3-bedroom-flat": 1300000,
      "self-contain": 320000,
      duplex: 2200000,
      room: 200000,
    },
    highlights: ["Modern Student Hostels", "Solar Backup Power Communities", "Close to Supermarkets & Gyms", "Reliable Water Supply"],
    description: "Sanrab is a modern residential cluster inside Tanke favored by senior students and faculty for quiet learning and reliable amenities.",
  },
  "kwara/oke-odo": {
    city: "Oke-Odo",
    name: "Oke-Odo (UNILORIN Gate Hub)",
    slug: "oke-odo",
    state: "Kwara",
    stateSlug: "kwara",
    powerBand: "Band B (16-20 hrs daily)",
    floodRisk: "Minimal / Zero flood risk",
    transitHub: "UNILORIN Permanent Site Road",
    campusProximity: "Walking distance to University of Ilorin Main Gate",
    medianRents: {
      apartment: 750000,
      "1-bedroom-flat": 480000,
      "2-bedroom-flat": 750000,
      "3-bedroom-flat": 1200000,
      "self-contain": 300000,
      duplex: 2000000,
      room: 180000,
    },
    highlights: ["Zero Commute to UNILORIN Gate", "Active Student Commerce", "Budget-Friendly Modern Lodges", "High Security Presence"],
    description: "Oke-Odo is located closest to the University of Ilorin main gate, making it the most convenient location for students seeking zero transit delays.",
  },
  "kwara/jalala": {
    city: "Jalala",
    name: "Jalala (University Staff Quarters Zone)",
    slug: "jalala",
    state: "Kwara",
    stateSlug: "kwara",
    powerBand: "Band A (20+ hrs daily)",
    floodRisk: "Minimal / Zero flood risk",
    transitHub: "University Internal Ring Road",
    campusProximity: "Inside UNILORIN Campus Area",
    medianRents: {
      apartment: 950000,
      "1-bedroom-flat": 600000,
      "2-bedroom-flat": 950000,
      "3-bedroom-flat": 1600000,
      "self-contain": 400000,
      duplex: 3000000,
      room: 250000,
    },
    highlights: ["Serene Academic Environment", "24/7 University Power Feed", "High Faculty Density", "Extensive Greenery"],
    description: "Jalala offers serene, low-density academic housing in Ilorin, surrounded by natural greenery and supported by superior grid uptime.",
  },
  "kwara/mark-junction": {
    city: "Mark Junction",
    name: "Mark Junction (Tanke Mark)",
    slug: "mark-junction",
    state: "Kwara",
    stateSlug: "kwara",
    powerBand: "Band B (16-20 hrs daily)",
    floodRisk: "Minimal / Zero flood risk",
    transitHub: "Tanke University Link",
    campusProximity: "5 mins to UNILORIN",
    medianRents: {
      apartment: 800000,
      "1-bedroom-flat": 520000,
      "2-bedroom-flat": 800000,
      "3-bedroom-flat": 1350000,
      "self-contain": 330000,
      duplex: 2300000,
      room: 210000,
    },
    highlights: ["Commercial Activity Core", "Popular Dining & Bakery Outlets", "Frequent Transit Access", "Newly Built Self-Contained Lodges"],
    description: "Mark Junction serves as a bustling nodal intersection in Tanke with easy access to banks, bakeries, transit parks, and modern private hostels.",
  },
  "kwara/fate": {
    city: "Fate",
    name: "Fate (Fate Road, Shoprite Axis)",
    slug: "fate",
    state: "Kwara",
    stateSlug: "kwara",
    powerBand: "Band A (20+ hrs daily)",
    floodRisk: "Minimal / Zero flood risk",
    transitHub: "Fate Road & Ilorin Ring Road",
    medianRents: {
      apartment: 1400000,
      "1-bedroom-flat": 800000,
      "2-bedroom-flat": 1400000,
      "3-bedroom-flat": 2200000,
      "self-contain": 500000,
      duplex: 4500000,
      room: 350000,
    },
    highlights: ["Proximity to Ilorin Palms Mall (Shoprite)", "Upscale Family Residences", "Band A Electricity Supply", "Paved Gated Avenues"],
    description: "Fate is one of Ilorin's most desirable upscale family communities, hosting prominent shopping centers, medical centers, and executive residences.",
  },
  "kwara/gra-ilorin": {
    city: "GRA Ilorin",
    name: "GRA Ilorin (Government Reserved Area)",
    slug: "gra-ilorin",
    state: "Kwara",
    stateSlug: "kwara",
    powerBand: "Band A (20+ hrs daily)",
    floodRisk: "Minimal / Zero flood risk",
    transitHub: "Ahmadu Bello Way & Offa Road",
    medianRents: {
      apartment: 2000000,
      "1-bedroom-flat": 1100000,
      "2-bedroom-flat": 2000000,
      "3-bedroom-flat": 3500000,
      "self-contain": 700000,
      duplex: 7000000,
      room: 500000,
    },
    highlights: ["Governor's Residence Axis", "Elite Security Patrols", "Calm Residential Atmosphere", "Large Compounds & Manicured Lawns"],
    description: "GRA Ilorin represents the traditional seat of calm, leafy affluence in Kwara State, home to diplomats, judges, and senior business executives.",
  },

  // OYO NEIGHBORHOODS (IBADAN)
  "oyo/bodija": {
    city: "Bodija",
    name: "Bodija (Old Bodija, New Bodija)",
    slug: "bodija",
    state: "Oyo",
    stateSlug: "oyo",
    powerBand: "Band A (20+ hrs daily)",
    floodRisk: "Low (Elevated terrain)",
    transitHub: "Secretariat Road & Bodija Market Railway Axis",
    medianRents: {
      apartment: 2200000,
      "1-bedroom-flat": 1200000,
      "2-bedroom-flat": 2200000,
      "3-bedroom-flat": 3500000,
      "self-contain": 650000,
      duplex: 6000000,
      room: 450000,
    },
    highlights: ["Ibadan's Premier Established Suburb", "Close to Oyo State Secretariat", "Broad Gated Streets", "High Influx of Remote Workers"],
    description: "Bodija is Ibadan's most recognized residential district, celebrated for high power stability, spacious plots, and proximity to state offices.",
  },
  "oyo/agbowo": {
    city: "Agbowo",
    name: "Agbowo (University of Ibadan Axis)",
    slug: "agbowo",
    state: "Oyo",
    stateSlug: "oyo",
    powerBand: "Band B (16-20 hrs daily)",
    floodRisk: "Low (Elevated terrain)",
    transitHub: "Ojo Expressway & UI Main Gate",
    campusProximity: "Adjacent to University of Ibadan (UI)",
    medianRents: {
      apartment: 1200000,
      "1-bedroom-flat": 650000,
      "2-bedroom-flat": 1200000,
      "3-bedroom-flat": 1900000,
      "self-contain": 380000,
      duplex: 3500000,
      room: 250000,
    },
    highlights: ["Direct Gate Access to UI", "Vibrant Academic Nightlife", "Budget-Friendly Student Housing", "High Rental Liquidity"],
    description: "Agbowo is situated right across the gates of Nigeria's premier university, UI, providing vibrant student lodges and affordable self-contained flats.",
  },
  "oyo/oluyole": {
    city: "Oluyole",
    name: "Oluyole Estate",
    slug: "oluyole",
    state: "Oyo",
    stateSlug: "oyo",
    powerBand: "Band B (16-20 hrs daily)",
    floodRisk: "Minimal / Zero flood risk",
    transitHub: "Ring Road & Ibadan-Lagos Tollgate corridor",
    medianRents: {
      apartment: 1800000,
      "1-bedroom-flat": 950000,
      "2-bedroom-flat": 1800000,
      "3-bedroom-flat": 2800000,
      "self-contain": 550000,
      duplex: 5000000,
      room: 400000,
    },
    highlights: ["Secure Gated Communities", "Direct Access to Lagos Tollgate", "Commercial & Industrial Links", "Family-Oriented"],
    description: "Oluyole Estate is a quiet residential estate in southwestern Ibadan offering effortless highway connections to Lagos and peaceful family living.",
  },

  // RIVERS NEIGHBORHOODS (PORT HARCOURT)
  "rivers/old-gra": {
    city: "Old GRA",
    name: "Old GRA Port Harcourt",
    slug: "old-gra",
    state: "Rivers",
    stateSlug: "rivers",
    powerBand: "Band A (20+ hrs daily)",
    floodRisk: "Minimal / Zero flood risk",
    transitHub: "Forces Avenue & Harley Street",
    medianRents: {
      apartment: 6000000,
      "1-bedroom-flat": 3000000,
      "2-bedroom-flat": 6000000,
      "3-bedroom-flat": 9500000,
      "self-contain": 1600000,
      duplex: 18000000,
      room: 1200000,
    },
    highlights: ["Government House & Executive Enclave", "Maximum Police Patrols", "Paved Tree-Lined Avenues", "Expatriate Serviced Housing"],
    description: "Old GRA is the most exclusive historic neighborhood in Port Harcourt, hosting top petroleum executives, state commissioners, and consulates.",
  },
  "rivers/peter-odili": {
    city: "Peter Odili",
    name: "Peter Odili Road Axis",
    slug: "peter-odili",
    state: "Rivers",
    stateSlug: "rivers",
    powerBand: "Band A (20+ hrs daily)",
    floodRisk: "Low (Elevated terrain)",
    transitHub: "Trans Amadi Link & Peter Odili Expressway",
    medianRents: {
      apartment: 4000000,
      "1-bedroom-flat": 2200000,
      "2-bedroom-flat": 4000000,
      "3-bedroom-flat": 6500000,
      "self-contain": 1100000,
      duplex: 12000000,
      room: 850000,
    },
    highlights: ["Modern Waterfront Estates", "Trans Amadi Industrial Link", "Gated Security Complexes", "High Oil Sector Tenancy"],
    description: "Peter Odili Road is a contemporary high-growth residential belt in Port Harcourt, popular with young energy sector professionals.",
  },

  // ENUGU NEIGHBORHOODS
  "enugu/independence-layout": {
    city: "Independence Layout",
    name: "Independence Layout Enugu",
    slug: "independence-layout",
    state: "Enugu",
    stateSlug: "enugu",
    powerBand: "Band A (20+ hrs daily)",
    floodRisk: "Minimal / Zero flood risk",
    transitHub: "Okpara Avenue & Presidential Road",
    medianRents: {
      apartment: 2400000,
      "1-bedroom-flat": 1300000,
      "2-bedroom-flat": 2400000,
      "3-bedroom-flat": 3800000,
      "self-contain": 700000,
      duplex: 7500000,
      room: 500000,
    },
    highlights: ["Enugu State Government Center", "Calm Residential Atmosphere", "Close to Bisalla Road Amenities", "Elite Security"],
    description: "Independence Layout is the administrative and elite residential core of Enugu, featuring grand avenues, diplomatic residences, and modern flats.",
  },
};

export const STANDARD_FEE_RATES = {
  cautionPercent: 0.10, // 10% refundable caution deposit
  legalPercent: 0.10,   // 10% legal / tenancy agreement fee
  agencyPercent: 0.10,  // 10% agent commission
  kalrentServiceFee: 0, // Zero hidden extra fees with KalRent Escrow
};
